function References() {
  return (
    <div>
      <h1 className="font-medium">
        References to other people&apos;s work used in this project
      </h1>
      <p>
        Design work:{" "}
        <a>https://dribbble.com/shots/22937655-Landing-page-for-Planoo</a>
      </p>
      <p>
        Home page hero: <a>Generated by Dall-E</a>
      </p>
      <p>
        <a target="_blank" href="https://icons8.com/icon/32292/instagram">
          Instagram
        </a>{" "}
        icon by{" "}
        <a target="_blank" href="https://icons8.com">
          Icons8
        </a>
      </p>
      <p>
        <a target="_blank" href="https://icons8.com/icon/gBDiZikxP0j3/facebook">
          Facebook
        </a>{" "}
        icon by{" "}
        <a target="_blank" href="https://icons8.com">
          Icons8
        </a>
      </p>
      <p>
        <a target="_blank" href="https://icons8.com/icon/fJp7hepMryiw/twitterx">
          Twitter
        </a>{" "}
        icon by{" "}
        <a target="_blank" href="https://icons8.com">
          Icons8
        </a>
      </p>{" "}
      <p>
        <a target="_blank" href="https://icons8.com/icon/447/linkedin">
          LinkedIn
        </a>{" "}
        icon by{" "}
        <a target="_blank" href="https://icons8.com">
          Icons8
        </a>
      </p>
    </div>
  );
}

export default References;
