function References() {
  return (
    <div>
      <h1 className="font-medium">References to other people&apos;s work used in this project</h1>
      <p>
        Design work:{" "}
        <a>https://dribbble.com/shots/22937655-Landing-page-for-Planoo</a>
      </p>
      <p>
        Home page hero: <a>Generated by Dall-E</a>
      </p>
    </div>
  );
}

export default References;
